function B = function_B_hover(Ixx,Iyy,Izz,L,Omega_w0,Omega_w1,alpha,d,mb,noload_speed,r,stall_torque)
%function_B_hover
%    B = function_B_hover(Ixx,Iyy,Izz,L,Omega_w0,Omega_w1,ALPHA,D,MB,NOLOAD_SPEED,R,STALL_TORQUE)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    22-Sep-2024 12:04:42

t2 = L.^2;
t3 = alpha.*2.0;
t4 = d.^2;
t6 = 1.0./Iyy;
t7 = 1.0./mb;
t8 = 1.0./noload_speed;
t9 = 1.0./r;
t11 = Ixx.*Iyy.*2.0;
t12 = Iyy.*Izz.*2.0;
t5 = cos(t3);
t10 = t9.^2;
t15 = Iyy.*mb.*t4;
t16 = Ixx.*mb.*t2.*2.0;
t17 = Izz.*mb.*t2.*2.0;
t18 = Omega_w0.*stall_torque.*t8;
t19 = Omega_w1.*stall_torque.*t8;
t13 = Ixx.*t5;
t14 = Izz.*t5;
t20 = t5.*t11;
t21 = t5.*t12;
t23 = -t15;
t25 = -t18;
t26 = -t19;
t22 = -t13;
t24 = Iyy.*t13.*-2.0;
t27 = stall_torque+t25;
t28 = stall_torque+t26;
t29 = mb.*t2.*t13.*2.0;
t30 = mb.*t2.*t14.*2.0;
t31 = -t29;
t32 = Ixx+Izz+t14+t22;
t33 = 1.0./t32;
t34 = t11+t12+t15+t16+t17+t21+t24+t30+t31;
t35 = t11+t12+t16+t17+t21+t23+t24+t30+t31;
B = reshape([0.0,(t6.*t7.*t10.*t27.*t33.*t34)./2.0,(t6.*t7.*t10.*t27.*t33.*t35)./2.0,-L.*t6.*t9.*t27,0.0,(t6.*t7.*t10.*t28.*t33.*t35)./2.0,(t6.*t7.*t10.*t28.*t33.*t34)./2.0,-L.*t6.*t9.*t28],[4,2]);
