function V = function_V_hover(Ixx,Izz,L,Omega_w0,Omega_w1,Theta,Theta_dot,alpha,d,mb,r)
%function_V_hover
%    V = function_V_hover(Ixx,Izz,L,Omega_w0,Omega_w1,Theta,Theta_dot,ALPHA,D,MB,R)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    22-Sep-2024 12:04:41

t2 = Theta+alpha;
t3 = L.^2;
t4 = Theta.*2.0;
t5 = Theta_dot.^2;
t6 = alpha.*2.0;
t7 = r.^2;
t10 = -Omega_w1;
t11 = 1.0./d.^2;
t8 = sin(t4);
t9 = sin(t2);
t12 = Omega_w0+t10;
t15 = t2.*2.0;
t13 = Ixx.*t8;
t14 = Izz.*t8;
t16 = sin(t15);
t19 = (L.*mb.*r.*t5.*t9)./2.0;
t17 = -t14;
t18 = mb.*t3.*t16;
t20 = -t19;
t21 = t13+t17+t18;
t22 = Theta_dot.*t7.*t11.*t12.*t21;
V = [t20+t22;t20-t22;t7.*t11.*t12.^2.*t21.*(-1.0./2.0)-(L.*Theta_dot.*mb.*r.*t9.*(Omega_w0+Omega_w1))./2.0];
