function G = function_G_hover(L,Theta,alpha,g,mb)
%function_G_hover
%    G = function_G_hover(L,Theta,ALPHA,g,MB)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    22-Sep-2024 12:04:41

G = [0.0;0.0;-L.*g.*mb.*sin(Theta+alpha)];
